#!/bin/bash

# Use next commands to see results (run them BEFORE statring this script):
# >>>>>>  sudo tail -f /var/log/syslog |  grep -v 'db_update' | grep -o time_of_.* | grep -o '[^_]*$' > output_file
# this will add "method_name time_spended_for_method" records into file @output_file@
# After this all just grep out data

if [[ "$#" == "1" ]]
then
	number_of_iterations=$1;
else
	number_of_iterations=20;
fi



for (( i=0;  i<=number_of_iterations; i++ )) ;
do
	test_user_name="test_user_$RANDOM";
	test_email="$RANDOM@$RANDOM";
        curl -d "{\"email\":\"$test_email\", \"login\":\"$test_user_name\",\"password\":\"VasjaPWD\"}"  http://localhost:81/service/registerUser
	sleep 1s
done
