#!/bin/bash

auth_token="MMMMMMMMMM";
channel="test_channel_$RANDOM";
date_=`date +'%d_%m_%Y_%H_%M_%S'`;
result_dir="./results_w_$date_/";
server_name="localhost";
steps_count=100;
step=1000;
symbs=`echo $steps_count | wc -m`;
file_name="MemoryUsage";


mkdir "$result_dir"
touch "$date_"
curl -d "{\"auth_token\":\"$auth_token\", \"name\":\"$channel\", \"description\":\"\", \"url\":\"\", \"activeRadius\":30}"  http://$server_name:81/service/addChannel 2>/dev/null

curl -d "{\"auth_token\":\"$auth_token\", \"channel\":\"$channel\"}" http://$server_name:81/service/subscribe 2>/dev/null
sleep 10s

for (( i=0;  i<=steps_count; i++ )) ;
do


	date_s=`date +'%d_%m_%Y_%H:%M:%S'`
	echo "$file_name iteration started at `date +'%d_%m_%Y_%H:%M:%S'`"
	ps -e -o vsz,rss,comm | grep fcgi | grep -o '^[0-9 ]*' >>"$result_dir/$file_name"
	./profiler $step writeTag $auth_token $channel 2>"$date_"
#	ssh root@$server_name "/opt/geo2tag/automation/clean_db.sh"
#	sleep 15s
	echo "$file_name iteration finished at `date +'%d_%m_%Y_%H_%M_%S'`"
done
