#!/bin/bash

channel="test_channel_$RANDOM";
result_dir="./results_r_`date +'%d_%m_%Y_%H_%M_%S'`/";
server_name="localhost";
response_login=`curl -d '{"login":"Mark","password":"test"}'  http://$server_name:81/service/login`;
auth_token=`echo $response_login | grep -Po '"\w+"' | grep -v "auth_token" | grep -v "errno" | grep -o '[^"]*'`;
echo "$auth_token"
# How much files be created
steps_count=10000;
# How much tags will be added at step 
step_size=1000;
read_requests_count=500;

mkdir "$result_dir"

curl -d "{\"auth_token\":\"$auth_token\", \"name\":\"$channel\", \"description\":\"\", \"url\":\"\", \"activeRadius\":30}"  http://$server_name:81/service/addChannel 2>/dev/null
curl -d "{\"auth_token\":\"$auth_token\", \"channel\":\"$channel\"}" http://$server_name:81/service/subscribe 2>/dev/null
sleep 10s
for (( i=0;  i<=steps_count; i++ )) ;
do
	echo "$i iteration"
	cool_num=`printf "%08d" $i`;
	./profiler $read_requests_count loadTags $auth_token 2>"$result_dir/$cool_num"
	./profiler $step_size writeTag $auth_token $channel 2>/dev/null 1>/dev/null

done
