######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 6 02:35:19 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              ../src/gui \
              ../src/common/inc \
              ../src/common/src \
              ../src/maps/inc \
              ../src/maps/src
INCLUDEPATH += . ../src/maps/inc ../src/common/inc ../src/gui

# Input
HEADERS += ../src/gui/MapForm.h \
           ../src/gui/MapWidget.h \
           ../src/common/inc/DefaultException.h \
           ../src/common/inc/Picture.h \
           ../src/common/inc/PngPicture.h \
           ../src/common/inc/DataMarks.h \
           ../src/maps/inc/CurlInitException.h \
           ../src/maps/inc/GoogleClientLogin.h \
           ../src/maps/inc/GoogleMapLoader.h \
           ../src/maps/inc/MapLoader.h \
           ../src/maps/inc/MapLoaderFactory.h
SOURCES += ../src/gui/MapForm.cpp \
           ../src/gui/MapWidget.cpp \
           ../src/common/src/DefaultException.cpp \
           ../src/common/src/Picture.cpp \
           ../src/common/src/PngPicture.cpp \
           ../src/common/src/DataMarks.cpp \
           ../src/maps/src/CurlInitException.cpp \
           ../src/maps/src/GoogleClientLogin.cpp \
           ../src/maps/src/GoogleMapLoader.cpp \
           ../src/maps/src/MapLoader.cpp \
           ../src/maps/src/MapLoaderFactory.cpp \
           ./main.cpp

LIBS += -lcurl

OBJECTS_DIR = .libs

MOC_DIR = .moc
