# #####################################################################
# Automatically generated by qmake (2.01a) ?? ????. 24 01:23:35 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network  xml

# Input
HEADERS += GetGoogleMarks.h \
    Position.h
SOURCES += main.cpp \
    GetGoogleMarks.cpp \
    Position.cpp
