#############################################################################
# Makefile for building: geo2tag
# Generated by qmake (2.01a) (Qt 4.6.3) on: Fri Oct 15 22:59:13 2010
# Project:  geo2tag.pro
# Template: subdirs
# Command: /home/ivan/development/qtsdk-2010.04/qt/bin/qmake -spec ../../../../development/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile geo2tag.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /home/ivan/development/qtsdk-2010.04/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/ivan/osll/geo2tag/branches/tracker-improoving/src/src.pro -spec /home/ivan/development/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/ivan/osll/geo2tag/branches/tracker-improoving/src/src.pro -spec /home/ivan/development/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: geo2tag.pro  ../../../../development/qtsdk-2010.04/qt/mkspecs/linux-g++/qmake.conf ../../../../development/qtsdk-2010.04/qt/mkspecs/common/g++.conf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/common/unix.conf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/common/linux.conf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/qconfig.pri \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/qt_config.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/default_pre.prf \
		config.pri \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/debug.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/default_post.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/mobility.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/warn_on.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/qt.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/moc.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/resources.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/uic.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/yacc.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/lex.prf \
		../../../../development/qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../../development/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile geo2tag.pro
../../../../development/qtsdk-2010.04/qt/mkspecs/common/g++.conf:
../../../../development/qtsdk-2010.04/qt/mkspecs/common/unix.conf:
../../../../development/qtsdk-2010.04/qt/mkspecs/common/linux.conf:
../../../../development/qtsdk-2010.04/qt/mkspecs/qconfig.pri:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/qt_config.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/default_pre.prf:
config.pri:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/debug.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/default_post.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/mobility.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/warn_on.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/qt.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/moc.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/resources.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/uic.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/yacc.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/lex.prf:
../../../../development/qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../../../development/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile geo2tag.pro

qmake_all: sub-src-qmake_all FORCE

make_default: sub-src-make_default FORCE
make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) check
check: sub-src-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

