#ifndef SUBSCRIBEDCHANNELSRESPONSEJSON_H
#define SUBSCRIBEDCHANNELSRESPONSEJSON_H

#include "ChannelListJSON.h"

typedef ChannelListResponseJSON SubscribedChannelsResponseJSON;
// SUBSCRIBEDCHANNELSRESPONSEJSON_H
#endif
