#ifndef SUBSCRIBEDCHANNELSRESPONSEJSON_H
#define SUBSCRIBEDCHANNELSRESPONSEJSON_H

#include "AvailableChannelsResponseJSON.h"

typedef AvailableChannelsResponseJSON SubscribedChannelsResponseJSON;
// SUBSCRIBEDCHANNELSRESPONSEJSON_H
#endif
