#ifndef SUBSCRIBEDCHANNELSRESPONSEJSON_H
#define SUBSCRIBEDCHANNELSRESPONSEJSON_H

#include "ChannelListJSON.h"

typedef ChannelListResponseJSON SubscribedChannelsResponseJSON;

#endif // SUBSCRIBEDCHANNELSRESPONSEJSON_H
