/*
 * originally generated by Glade.
 */

GtkWidget* create_gODBCConfig (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_dialog4 (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_dialog6 (void);
GtkWidget* create_dialog7 (void);
GtkWidget* create_dialog8 (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window5 (void);
void on_browse_clicked(GtkButton*,gpointer);
