/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>
#include <odbcconfig.h>

int
main (int argc, char *argv[])
{
  GtkWidget *odbc;
  GtkWidget *window;

  gnome_init ("gODBCConfig", VERSION, argc, argv);

  odbc = gtk_odbcconfig_new();

  window = gtk_window_new( GTK_WINDOW_TOPLEVEL );
  gtk_window_set_title (GTK_WINDOW (window), 
					_("gODBCConfig - ODBC Data Source Administrator"));

  odbc = gtk_odbcconfig_new();

  gtk_container_add(GTK_CONTAINER(window),odbc);

  gtk_widget_show (odbc);
  gtk_widget_show (window);

  gtk_main ();

  return 0;
}
