######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 3 16:36:03 2012
######################################################################

TEMPLATE = subdirs 
CONFIG +=ordered
#DEPENDPATH +=
#INCLUDEPATH += 


SUBDIRS += \
	src \
	tst 

