.TH ODBCConfig 1 "2nd Mar 2002" UnixODBC "UnixODBC Reference"
.SH NAME
ODBCConfig \- Qt-based ODBC Data Source Administrator
.SH SYNOPSIS
.B ODBCConfig
.RI "[ " generic-options " ]"
.SH DESCRIPTION
This  manual  page  documents briefly the
.B ODBCConfig
command.  This manual page was written for the Debian GNU/Linux 
distribution because the original program does not have a manual page.
.PP
.B ODBCConfig
is a graphical configuration tool that allows configuration of ODBC 
drivers (as the superuser) and Data Source Names (as any user).  
Configuration of File, System, and User DSNs is supported, using the 
graphical driver
.I setup libraries
provided by unixODBC.
.SH FILES
.IR /etc/odbcinst.ini ", " /etc/odbc.ini ", " $HOME/.odbc.ini
.SH AUTHOR
This manual page was written by Steve Langasek <vorlon@debian.org> for
the Debian package of unixODBC.
.SH SEE ALSO
.BR odbcinst(1) ", " gODBCConfig(1)
