######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 18 13:38:38 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += getcolor.cpp \
    testwidget.cpp

HEADERS += \
    testwidget.h
