#!/bin/bash

auth_token="MMMMMMMMMM";
channel="test_channel_$RANDOM";
result_dir="./results/";
# How much files be created
steps_count=100;
# How much tags will be added at step 
step_size=1000;
read_requests_count=10000;

curl -d "{\"auth_token\":\"$auth_token\", \"name\":\"$channel\", \"description\":\"\", \"url\":\"\", \"activeRadius\":30}"  http://tracks.osll.spb.ru:81/service/addChannel 2>/dev/null
curl -d "{\"auth_token\":\"$auth_token\", \"channel\":\"$channel\"}" http://tracks.osll.spb.ru:81/service/subscribe 2>/dev/null
sleep 10s
for (( i=0;  i<=steps_count; i++ )) ;
do
	echo "$i iteration"
	./profiler $read_requests_count loadTags $auth_token 2>"$result_dir"_$(( step_size*i ))
	./profiler $step_size writeTag $auth_token $channel 2>/dev/null 1>/dev/null

done
